[package]
name = "rintty"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
crossterm = "0.29.0"
libc = "0.2.174"
nix = { version = "0.30.1", features = ["fs", "process", "term", "user"] }
pam = "0.7.0"
ratatui = "0.29.0"
vte = "0.15.0"

